/**
 * 
 * @author Matt Peters 
 * @author Joel Farquhar 
 * @author Nathan Joseph
 *
 */
public enum GameMode{
	STARTSCREEN, SCUBASTART, SCUBATUTORIAL,ANIMALTUTORIAL, ANIMALTUTORIALRUN, SCUBATUTORIALRUN, SCUBARUN, SCUBAEND, FFTITLESTART, FFTITLE, FFTITLEEND, QUIZSTART, QUIZRUN, QUIZEND, ANIMALSTART, ANIMALRUN, ANIMALEND
}
